# Generated by Django 4.1.4 on 2023-01-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
