# Generated by Django 4.1.4 on 2023-01-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCatgoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Nombre de la pelicula')),
                ('marca', models.CharField(max_length=20, verbose_name='Rating')),
                ('modelo', models.TextField()),
                ('sinopsis', models.TextField()),
                ('encuentrala', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
